sudo: required
services:
  - docker

before_install:
  - docker build -t jwj0831/my-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jwj0831/my-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "my-docker-react"
  env: "MyDockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-439361245083"
  bucket_path: "my-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
